### ISSUE TITLE
amexio-form property bindings

### ISSUE THREAD

**Issue by trithesh** [meta-magic/Amexio-VSC-Extension#1]
hi, I have been trying out amexio, so I installed this extension in vs code,
the amexio-form which is created by snippet is emitting property bindings in those it is consisting of [footer]=" false". it is showing an error of no such property.

**Comment by sagarthecook** [comment]
Hi @trithesh 
sorry for late response we will resolve this issue and update you soon..

**Comment by rashmithakkar** [comment]
Hi @trithesh ,

We have solved above issue. Please reinstall the amexio extension. (3.2.0)
